### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by turto1se** [upais/ZONT-to-Home_Assistant#1]
Добрый день, а можно инструкцию ко всему этому? а то лазить по всем ссылкам ой как не удобно, да и информация по ним уже протухла.
Куда добавлять код?
прочие нюансы, коих много.
Можно прямую связь с Вами?
тг @brebigor

**Comment by upais** [comment]
Приветствую.
Обновил инструкцию, добавил свою конфигурацию. Красивости форматирования позже добавлю, Github как-то по своему форматирует текст, надо разобраться.
Если что-то требуется уточнить в инструкции - пишите, дополню.

Прошелся по всем ссылкам - нормально там все.
